server {
  listen 6566;
  auth_basic "Feast Feature Server";
  auth_basic_user_file /etc/nginx/.htpasswd;

  location / {
    proxy_pass http://feature-server:6566;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
  }
}

server {
  listen 6572;
  auth_basic "Feast Registry";
  auth_basic_user_file /etc/nginx/.htpasswd;

  location / {
    proxy_pass http://registry-server:6572;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
